---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: traefik-crd-source
  namespace: flux-system
spec:
  interval: 30m
  url: ssh://github.com/traefik/traefik-helm-chart.git
  secretRef:
    name: flux-system
  ref:
    # renovate: registryUrl=https://traefik.github.io/charts/ chart=traefik
    tag: v41.4.0
  ignore: |
    # exclude all
    /*
    # path to crds
    !/traefik/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 30m
  prune: false
  sourceRef:
    kind: GitRepository
    name: traefik-crd-source
