---
name: Deploy softBarry to GHCR

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ./Dockerfiles/pihole-*

env:
  registry: ghcr.io
  imageName: softbarry
  dockerfile_path: ./Dockerfiles
  dockerfile: ./Dockerfiles/pihole-keepalived.Dockerfile

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4
        with:
          registry: ${{ env.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: ${{ env.dockerfile_path }}
          file: ${{ env.dockerfile }}
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.imageName }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ env.imageName }}:latest
