---
name: Scan IaC

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "cluster/*"
      - "provision/*"
      - "Dockerfiles/*"
      - "k8s/*"

env:
  SCAN_ALL: ${{ github.event_name == 'workflow_dispatch' }}

jobs:
  scan-iac-mode:
    name: Scan IaC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@d2a0b60797ff03db6132bd4e2b293f9b37081297 # master
        with:
          scan-type: "config"
          hide-progress: false
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4
        with:
          sarif_file: trivy-results.sarif
